(function(e){function t(t){for(var o,
a,
r=t[0],
c=t[1],
u=t[2],
l=0,
d=[];l<r.length;l++)a=r[l],
Object.prototype.hasOwnProperty.call(i,
a)&&i[a]&&d.push(i[a][0]),
i[a]=0;for(o in c)Object.prototype.hasOwnProperty.call(c,
o)&&(e[o]=c[o]);f&&f(t);while(d.length)d.shift()();return s.push.apply(s,
u||[]),
n()}function n(){for(var e,
t=0;t<s.length;t++){for(var n=s[t],
o=!0,
a=1;a<n.length;a++){var r=n[a];0!==i[r]&&(o=!1)}o&&(s.splice(t--,
1),
e=c(c.s=n[0]))}return e}var o={},
a={app:0},
i={app:0},
s=[];function r(e){return c.p+"statics/js/"+({about:"about"}[e]||e)+"."+{about:"271037b8",
"chunk-2c815b76":"5b1dcb68",
"chunk-35e8c89d":"c97e43a2",
"chunk-538e9ed4":"0d918e65",
"chunk-56967e76":"caf6c2e7",
"chunk-6122a942":"725ac92f",
"chunk-61383428":"60cf1bf4",
"chunk-86a93e48":"1dc859d2",
"chunk-91abb970":"c43e4756",
"chunk-ae0974fa":"f1adafa7",
"chunk-523fbc9c":"af0664e1",
"chunk-e9f134e6":"dc0829d6",
"chunk-439b207b":"9cf7ef7b",
"chunk-282a6af1":"03a36613"}[e]+".js"}function c(t){if(o[t])return o[t].exports;var n=o[t]={i:t,
l:!1,
exports:{}};return e[t].call(n.exports,
n,
n.exports,
c),
n.l=!0,
n.exports}c.e=function(e){var t=[],
n={"chunk-2c815b76":1,
"chunk-35e8c89d":1,
"chunk-538e9ed4":1,
"chunk-56967e76":1,
"chunk-6122a942":1,
"chunk-61383428":1,
"chunk-69861bb0":1,
"chunk-86a93e48":1,
"chunk-91abb970":1,
"chunk-ae0974fa":1,
"chunk-523fbc9c":1,
"chunk-e9f134e6":1,
"chunk-439b207b":1,
"chunk-282a6af1":1};a[e]?t.push(a[e]):0!==a[e]&&n[e]&&t.push(a[e]=new Promise((function(t,
n){for(var o="statics/css/"+({about:"about"}[e]||e)+"."+{about:"31d6cfe0",
"chunk-2c815b76":"b919846b",
"chunk-35e8c89d":"2724fa78",
"chunk-538e9ed4":"22e160c0",
"chunk-56967e76":"06b88cbd",
"chunk-6122a942":"22beef4e",
"chunk-61383428":"cbd88a4b",
"chunk-69861bb0":"57a2b274",
"chunk-86a93e48":"f13fb619",
"chunk-91abb970":"003f387e",
"chunk-ae0974fa":"9ec9921c",
"chunk-523fbc9c":"9309189f",
"chunk-e9f134e6":"e813df88",
"chunk-439b207b":"0e433876",
"chunk-282a6af1":"f5c97200"}[e]+".css",
i=c.p+o,
s=document.getElementsByTagName("link"),
r=0;r<s.length;r++){var u=s[r],
l=u.getAttribute("data-href")||u.getAttribute("href");if("stylesheet"===u.rel&&(l===o||l===i))return t()}var d=document.getElementsByTagName("style");for(r=0;r<d.length;r++){u=d[r],
l=u.getAttribute("data-href");if(l===o||l===i)return t()}var f=document.createElement("link");f.rel="stylesheet",
f.type="text/css",
f.onload=t,
f.onerror=function(t){var o=t&&t.target&&t.target.src||i,
s=new Error("Loading CSS chunk "+e+" failed.\n("+o+")");s.code="CSS_CHUNK_LOAD_FAILED",
s.request=o,
delete a[e],
f.parentNode.removeChild(f),
n(s)},
f.href=i;var g=document.getElementsByTagName("head")[0];g.appendChild(f)})).then((function(){a[e]=0})));var o=i[e];if(0!==o)if(o)t.push(o[2]);else{var s=new Promise((function(t,
n){o=i[e]=[t,
n]}));t.push(o[2]=s);var u,
l=document.createElement("script");l.charset="utf-8",
l.timeout=12000,
c.nc&&l.setAttribute("nonce",
c.nc),
l.src=r(e);var d=new Error;u=function(t){l.onerror=l.onload=null,
clearTimeout(f);var n=i[e];if(0!==n){if(n){var o=t&&("load"===t.type?"missing":t.type),
a=t&&t.target&&t.target.src;d.message="Loading chunk "+e+" failed.\n("+o+": "+a+")",
d.name="ChunkLoadError",
d.type=o,
d.request=a,
n[1](d)}i[e]=void 0}};var f=setTimeout((function(){u({type:"timeout",
target:l})}),
12e4);l.onerror=l.onload=u,
document.head.appendChild(l)}return Promise.all(t)},
c.m=e,
c.c=o,
c.d=function(e,
t,
n){c.o(e,
t)||Object.defineProperty(e,
t,
{enumerable:!0,
get:n})},
c.r=function(e){"undefined"!==typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,
Symbol.toStringTag,
{value:"Module"}),
Object.defineProperty(e,
"__esModule",
{value:!0})},
c.t=function(e,
t){if(1&t&&(e=c(e)),
8&t)return e;if(4&t&&"object"===typeof e&&e&&e.__esModule)return e;var n=Object.create(null);if(c.r(n),
Object.defineProperty(n,
"default",
{enumerable:!0,
value:e}),
2&t&&"string"!=typeof e)for(var o in e)c.d(n,
o,
function(t){return e[t]}.bind(null,
o));return n},
c.n=function(e){var t=e&&e.__esModule?function(){return e["default"]}:function(){return e};return c.d(t,
"a",
t),
t},
c.o=function(e,
t){return Object.prototype.hasOwnProperty.call(e,
t)},
c.p="/play/",
c.oe=function(e){throw console.error(e),
e};var u=window["webpackJsonp"]=window["webpackJsonp"]||[],
l=u.push.bind(u);u.push=t,
u=u.slice();for(var d=0;d<u.length;d++)t(u[d]);var f=l;s.push([0,
"chunk-vendors"]),
n()})({0:function(e,
t,
n){e.exports=n("56d7")},
1376:function(e,
t,
n){e.exports={fadeIn:"animated_fadeIn_rQamn",
fadeInTo4:"animated_fadeInTo4_3gbao",
fadeOut4:"animated_fadeOut4_2UBsP",
zoomIn:"animated_zoomIn_pxmqu",
zoomInSmall:"animated_zoomInSmall_2EDDR",
fadeInTo9:"animated_fadeInTo9_2qrGZ",
scaleIn:"animated_scaleIn_lRQzu",
openUp:"animated_openUp_1Osd1",
moveToTop:"animated_moveToTop_3DTSg",
moveToButtom:"animated_moveToButtom_1J-TM",
headmoveToTop:"animated_headmoveToTop_3xGKp",
headmoveToButtom:"animated_headmoveToButtom_20060",
showlogo:"animated_showlogo_38pFZ",
hidelogo:"animated_hidelogo_2Ghj-",
showSearch:"animated_showSearch_hyeli",
hideSearch:"animated_hideSearch_2EoJ7",
animated:"animated_animated_3yMyD",
infinite:"animated_infinite_34O6e",
"delay-1s":"animated_delay-1s_TTem9",
"delay-2s":"animated_delay-2s_gqvLq",
"delay-3s":"animated_delay-3s_2PgAr",
"delay-4s":"animated_delay-4s_1yoOQ",
"delay-5s":"animated_delay-5s_1h7Tw",
fast:"animated_fast_2oMAK",
faster:"animated_faster_10YeL",
slow:"animated_slow_3oWRp",
slower:"animated_slower_1RIch",
fadeIndTo4:"animated_fadeIndTo4_1n-nS",
fadeIndTo9:"animated_fadeIndTo9_aagVq"}},
"14d9":function(e,
t,
n){"use strict";var o=n("153d"),
a=n.n(o);a.a},
"153d":function(e,
t,
n){},
"1be4":function(e,
t){e.exports="data:image/png;base64,
iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAAAAXNSR0IArs4c6QAAAihJREFUSA29l0tOwzAURRs+UiVaCQoVAiYwYMCUFSDmrIT1wHJgBeyBEQiVtkiAFIlPuMdy0tTkJWmU9kqvduwXHz//4kadGkqSJJJbV9bz6YZSDH17i5V+yOIoihKlpaJBUwKuqXJbtiNbNx3nK370OJW9qQO/81WzJxMsaF9uQ1ka2eytejlGYiT4e5H7P7Af1l05D4peaFA20TvjcPjnwB56IEfmsk0x9895OHOYF5G2DaV92qTtTBnYz2lbw5sBcpmBZ7giB1YBKQtp2Rp6VieNmC1jrd4j1V3Jtmr0Ch98Dw1fGLA6G+oBC4x9aulcFReyM9mN7FNWJKDXsn0ZB8iTrEg7Yk6JmBOp7HC4U/2LjAZpGECoPBTf+9Ah9wyrC7hqFRMhkVrwEFo2KmrGqZdGnBZYqQVvAoXRjTTeJ8psWsSgPARRzRQwGnUixR99AT5VZu4Ec1X2Tx6O16JQ3nH7l8zKxRzzFamrfLREai24qva+FwGHUOYUawJ3YG4OVSqCstKxJvCYiPlklcmCpu80gX8AJmKuK5YuVVG1ZYDfytJh5x1LsGK3jbSl+BzuGZ58JDivOToBlInRAfogs87qV10IJimYyI9l1hdKVa2IHfQo8C/ADhklI/JLFpc/d/N0YGAq4DbIxWxZmniGaz8De9pYadUqb9Ix2qTtTP/OaC00ylZ7vc26o4w60FcylDVdcItd6AM4U7HavzBBBxj+Vv+0/QFiSrYWPG7i7wAAAABJRU5ErkJggg=="},
"1e04":function(e,
t,
n){"use strict";var o=n("f753"),
a=n.n(o),
i={};["get",
"post"].map((function(e){i[e]=function(){return a.a[e].apply(a.a,
arguments).then((function(e){if(e){var t=e.data;return t}}))}})),
t["a"]=i},
"2adf":function(e,
t,
n){"use strict";var o=n("460c"),
a=n.n(o);a.a},
"3d01":function(e,
t,
n){"use strict";n.r(t);var o=function(){var e=this,
t=e.$createElement,
o=e._self._c||t;return o("header",
{staticClass:"mainNav"},
[o("div",
{staticClass:"logo",
attrs:{title:"返回主页"},
on:{click:e.toIndex}},
[o("img",
{attrs:{src:n("cf05"),
alt:"集智学园"}}),
o("h1",
[e._v("集智学园")])]),
o("div",
{staticClass:"right"},
[o("div",
{staticClass:"search-input"},
[o("i",
{staticClass:"iconfont icon-search"}),
o("input",
{directives:[{name:"model",
rawName:"v-model",
value:e.searchValue,
expression:"searchValue"}],
attrs:{type:"text",
placeholder:"请输入搜索关键字"},
domProps:{value:e.searchValue},
on:{keydown:e.search,
input:function(t){t.target.composing||(e.searchValue=t.target.value)}}})]),
o("ul",
{staticClass:"cataloglist"},
e._l(e.$store.state.catalogList,
(function(t){return o("li",
{key:t.catalog_id||t.id,
staticClass:"catalog-item",
on:{click:function(n){return e.tocatalog(t)}}},
[e._v(e._s(t.catalog_title||t.title))])})),
0),
o("div",
{staticClass:"login"},
[e.loginState?o("div",
{staticClass:"user-pic"},
[o("img",
{attrs:{src:e.userInfo.pic||"@/assets/defaultImg.jpg",
alt:"集智学园",
onerror:"this.src='http://qiniu.swarma.org/image/user-default.gif'"},
on:{click:function(t){e.showUser=!e.showUser}}}),
o("span",
{staticClass:"score",
on:{mouseover:function(t){e.showScoreText=!0},
mouseout:function(t){e.showScoreText=!1},
click:e.toScore}},
[e._v("\n          积分: "+e._s(e.score||0)+"\n          "),
o("i",
{staticClass:"iconfont question"},
[e._v("?")])])]):o("button",
{staticClass:"login-btn",
on:{click:e.loginBtn}},
[e._v("登录 / 注册")]),
e.showUser?o("ul",
{staticClass:"user-modal"},
[o("span",
{staticClass:"trangle"}),
o("li",
{staticClass:"user-item",
on:{click:function(t){return e.toUserCenter()}}},
[e._v("个人中心")]),
o("li",
{staticClass:"user-item",
on:{click:function(t){return e.toUserCenter(4)}}},
[e._v("我的课表")]),
o("li",
{staticClass:"user-item",
on:{click:function(t){return e.toNewversion()}}},
[e._v("前往知识星空")]),
o("li",
{staticClass:"user-item",
on:{click:e.logoutBtn}},
[e._v("退出登录")])]):e._e()])])])},
a=[],
i=(n("efce"),
n("4634"),
n("ed8b"),
n("e4e2")),
s=n("c24f"),
r=n("08c1");function c(e,
t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);t&&(o=o.filter((function(t){return Object.getOwnPropertyDescriptor(e,
t).enumerable}))),
n.push.apply(n,
o)}return n}function u(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?c(n,
!0).forEach((function(t){Object(i["a"])(e,
t,
n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,
Object.getOwnPropertyDescriptors(n)):c(n).forEach((function(t){Object.defineProperty(e,
t,
Object.getOwnPropertyDescriptor(n,
t))}))}return e}var l={data:function(){return{showScoreText:!1,
showUser:!1,
searchValue:""}},
computed:Object(r["c"])({score:function(e){return e.User.score},
loginState:function(e){return e.User.loginState},
userInfo:function(e){return e.User.userInfo},
courseDetail:function(e){return e.courseDetail}}),
methods:u({},
Object(r["b"])(["openLoginDialog",
"setLoading"]),
{showHideScoreText:function(e){this.showScoreText=!0},
search:function(e){var t=this;13===e.keyCode&&(this.$router.push({name:"search",
query:{value:this.searchValue}}),
this.$store.commit("setLoading",
!0),
this.$store.dispatch("Search/setSearchList",
{value:this.searchValue,
page:1}).then((function(e){t.$store.commit("setLoading",
!1)})))},
loginBtn:function(){this.openLoginDialog(!0)},
logoutBtn:function(){var e=this;this.setLoading(!0),
s["a"].loginOut().then((function(t){e.setLoading(!1),
"1"===t.code&&(e.$message.success("您已退出登录"),
e.showUser=!1,
e.$store.dispatch("User/setUserinfo"),
e.$store.dispatch("setCourseDetail",
e.courseDetail.cid))}))},
toRouter:function(e){"record"===e?this.$router.push({name:e,
query:{type:2}}):this.$router.push({name:e})},
toIndex:function(){window.open("/")},
toUserCenter:function(){var e=arguments.length>0&&void 0!==arguments[0]?arguments[0]:2;this.$router.push({name:"record",
query:{type:e}})},
toNewversion:function(){window.open("/mobileinterface/oldtonew")},
tocatalog:function(e){e.catalog_id?window.open("/catalog=".concat(e.catalog_id)):window.open("/courseMap")},
toScore:function(){this.$router.push({name:"score"})}})},
d=l,
f=(n("14d9"),
n("4e82")),
g=Object(f["a"])(d,
o,
a,
!1,
null,
"19b4152a",
null);t["default"]=g.exports},
"460c":function(e,
t,
n){},
"4c22":function(e,
t,
n){},
"56d7":function(e,
t,
n){"use strict";n.r(t);n("63ff"),
n("e6d1"),
n("ebec");var o=n("953a"),
a=(n("80bc"),
n("19dd"),
n("1e27")),
i=n.n(a),
s=(n("ae5f"),
n("f6a8")),
r=n.n(s),
c=(n("d24b"),
n("12fa")),
u=n.n(c),
l=(n("fc5c"),
n("3e62")),
d=n.n(l),
f=(n("96dd"),
n("a60a"),
n("e783"),
n("8b1f"),
n("6e6d")),
g=function(){var e=this,
t=e.$createElement,
n=e._self._c||t;return n("div",
{attrs:{id:"app"}},
[e.$store.state.loading?n("Loading"):e._e(),
n("noticeBar"),
e.showLoginDialog||e.showWechatpayDialog||e.showAlipayDialog?n("LoginDialog",
{ref:"loginDialog"}):e._e(),
n("router-view"),
n("command")],
1)},
p=[],
h=(n("cc1d"),
function(){var e=this,
t=e.$createElement;e._self._c;return e._m(0)}),
m=[function(){var e=this,
t=e.$createElement,
n=e._self._c||t;return n("div",
{attrs:{id:"loading"}},
[n("span",
{staticClass:"icon iconfont icon-jiazai rotateInfinit"})])}],
w={data:function(){return{}}},
v=w,
b=(n("2adf"),
n("bf39"),
n("4e82")),
y=Object(b["a"])(v,
h,
m,
!1,
null,
"c044e00a",
null),
_=y.exports,
C=function(){var e=this,
t=e.$createElement,
o=e._self._c||t;return o("div",
{attrs:{id:"dialog"}},
[e.showLoginDialog?o("div",
{staticClass:"wrapper login animated fadeIn"},
[o("img",
{staticClass:"close-btn",
attrs:{src:n("1be4"),
alt:""},
on:{click:e.closeDialog}}),
"wechat"===e.loginType||"phone"===e.loginType?o("ul",
{staticClass:"tab"},
[o("li",
{staticClass:"tab-item",
class:"wechat"===e.loginType?"active":"",
on:{click:function(t){return e.changeLoginType("wechat")}}},
[e._v("微信登录")]),
o("li",
{staticClass:"tab-item",
class:"phone"===e.loginType?"active":"",
on:{click:function(t){return e.changeLoginType("phone")}}},
[e._v("用户名登录")])]):e._e(),
o("div",
{directives:[{name:"show",
rawName:"v-show",
value:"wechat"===e.loginType,
expression:"loginType === 'wechat'"}]},
[o("div",
{staticClass:"tip"},
[e._v("新用户扫码即注册")]),
o("iframe",
{staticClass:"login_container",
attrs:{src:"/wxlogin.html",
frameborder:"0"}})]),
"phone"===e.loginType?o("div",
{staticClass:"login_phone form"},
[o("div",
{staticStyle:{position:"relative"}},
[o("i",
{staticClass:"icon iconfont icon-yonghuming"}),
o("input",
{directives:[{name:"model",
rawName:"v-model",
value:e.login.username,
expression:"login.username"}],
staticClass:"input",
attrs:{type:"text",
autocomplete:"off",
placeholder:"用户名/手机号"},
domProps:{value:e.login.username},
on:{keydown:e.loginkeyDown,
input:function(t){t.target.composing||e.$set(e.login,
"username",
t.target.value)}}})]),
o("div",
{staticStyle:{position:"relative"}},
[o("i",
{staticClass:"icon iconfont icon-mima"}),
o("input",
{directives:[{name:"model",
rawName:"v-model",
value:e.login.password,
expression:"login.password"}],
staticClass:"input",
attrs:{autocomplete:"off",
type:"password",
placeholder:"密码"},
domProps:{value:e.login.password},
on:{keydown:e.loginkeyDown,
input:function(t){t.target.composing||e.$set(e.login,
"password",
t.target.value)}}})]),
o("div",
{staticClass:"btn-group"},
[o("span",
{on:{click:function(t){return e.changeLoginType("forget")}}},
[e._v("忘记密码")])]),
o("div",
{staticClass:"login-btn",
on:{click:e.loginBtn}},
[e._v("登 录")])]):e._e(),
"register"===e.loginType?o("div",
{staticClass:"regester form"},
[o("div",
{staticStyle:{position:"relative"}},
[o("i",
{staticClass:"icon iconfont icon-yonghuming"}),
o("input",
{directives:[{name:"model",
rawName:"v-model",
value:e.register.username,
expression:"register.username"}],
staticClass:"input",
attrs:{type:"text",
autocomplete:"off",
placeholder:"用户名"},
domProps:{value:e.register.username},
on:{keydown:e.registerKeyDown,
input:function(t){t.target.composing||e.$set(e.register,
"username",
t.target.value)}}})]),
o("div",
{staticStyle:{position:"relative"}},
[o("i",
{staticClass:"icon iconfont icon-mima"}),
o("input",
{directives:[{name:"model",
rawName:"v-model",
value:e.register.mobile,
expression:"register.mobile"}],
staticClass:"input",
attrs:{type:"text",
autocomplete:"off",
placeholder:"手机号"},
domProps:{value:e.register.mobile},
on:{keydown:e.registerKeyDown,
input:function(t){t.target.composing||e.$set(e.register,
"mobile",
t.target.value)}}})]),
o("div",
{staticStyle:{position:"relative"}},
[o("i",
{staticClass:"icon iconfont icon-mima"}),
o("input",
{directives:[{name:"model",
rawName:"v-model",
value:e.register.code,
expression:"register.code"}],
staticClass:"input",
attrs:{type:"text",
autocomplete:"off",
placeholder:"验证码"},
domProps:{value:e.register.code},
on:{keydown:e.registerKeyDown,
input:function(t){t.target.composing||e.$set(e.register,
"code",
t.target.value)}}}),
o("span",
{staticClass:"codeBtn",
on:{click:function(t){return e.codeBtn(e.register.mobile)}}},
[e._v("发送验证码")])]),
o("div",
{staticStyle:{position:"relative"}},
[o("i",
{staticClass:"icon iconfont icon-mima"}),
o("input",
{directives:[{name:"model",
rawName:"v-model",
value:e.register.pwd,
expression:"register.pwd"}],
staticClass:"input",
attrs:{type:"password",
autocomplete:"off",
placeholder:"密码"},
domProps:{value:e.register.pwd},
on:{keydown:e.registerKeyDown,
input:function(t){t.target.composing||e.$set(e.register,
"pwd",
t.target.value)}}})]),
o("div",
{staticStyle:{position:"relative"}},
[o("i",
{staticClass:"icon iconfont icon-mima"}),
o("input",
{directives:[{name:"model",
rawName:"v-model",
value:e.register.repwd,
expression:"register.repwd"}],
staticClass:"input",
attrs:{type:"password",
autocomplete:"off",
placeholder:"确认密码"},
domProps:{value:e.register.repwd},
on:{keydown:e.registerKeyDown,
input:function(t){t.target.composing||e.$set(e.register,
"repwd",
t.target.value)}}})]),
o("div",
{staticClass:"btn-group"},
[o("span",
{on:{click:function(t){return e.changeLoginType("phone")}}},
[e._v("返回登录")])]),
o("div",
{staticClass:"login-btn",
on:{click:e.registerBtn}},
[e._v("注册")])]):e._e(),
"forget"===e.loginType?o("div",
{staticClass:"regester form"},
[o("div",
{staticStyle:{position:"relative"}},
[o("i",
{staticClass:"icon iconfont icon-mima"}),
o("input",
{directives:[{name:"model",
rawName:"v-model",
value:e.resetPassword.remobile,
expression:"resetPassword.remobile"}],
staticClass:"input",
attrs:{autocomplete:"off",
type:"text",
placeholder:"手机号"},
domProps:{value:e.resetPassword.remobile},
on:{keydown:e.forgetPasswordKeyDown,
input:function(t){t.target.composing||e.$set(e.resetPassword,
"remobile",
t.target.value)}}})]),
o("div",
{staticStyle:{position:"relative"}},
[o("i",
{staticClass:"icon iconfont icon-mima"}),
o("input",
{directives:[{name:"model",
rawName:"v-model",
value:e.resetPassword.recode,
expression:"resetPassword.recode"}],
staticClass:"input",
attrs:{autocomplete:"off",
type:"text",
placeholder:"验证码"},
domProps:{value:e.resetPassword.recode},
on:{keydown:e.forgetPasswordKeyDown,
input:function(t){t.target.composing||e.$set(e.resetPassword,
"recode",
t.target.value)}}}),
o("span",
{staticClass:"codeBtn",
on:{click:function(t){return e.codeBtn(e.resetPassword.remobile)}}},
[e._v("发送验证码")])]),
o("div",
{staticStyle:{position:"relative"}},
[o("i",
{staticClass:"icon iconfont icon-mima"}),
o("input",
{directives:[{name:"model",
rawName:"v-model",
value:e.resetPassword.newpwd,
expression:"resetPassword.newpwd"}],
staticClass:"input",
attrs:{autocomplete:"off",
type:"password",
placeholder:"密码"},
domProps:{value:e.resetPassword.newpwd},
on:{keydown:e.forgetPasswordKeyDown,
input:function(t){t.target.composing||e.$set(e.resetPassword,
"newpwd",
t.target.value)}}})]),
o("div",
{staticStyle:{position:"relative"}},
[o("i",
{staticClass:"icon iconfont icon-mima"}),
o("input",
{directives:[{name:"model",
rawName:"v-model",
value:e.resetPassword.repwd,
expression:"resetPassword.repwd"}],
staticClass:"input",
attrs:{autocomplete:"off",
type:"password",
placeholder:"确认密码"},
domProps:{value:e.resetPassword.repwd},
on:{keydown:e.forgetPasswordKeyDown,
input:function(t){t.target.composing||e.$set(e.resetPassword,
"repwd",
t.target.value)}}})]),
o("div",
{staticClass:"btn-group"},
[o("span",
{on:{click:function(t){return e.changeLoginType("phone")}}},
[e._v("返回登录")])]),
o("div",
{staticClass:"login-btn",
on:{click:e.forgetPassword}},
[e._v("确认修改")])]):e._e()]):e._e(),
e.showWechatpayDialog?o("div",
{staticClass:"wrapper login animated fadeIn"},
[o("img",
{staticClass:"close-btn",
attrs:{src:n("1be4"),
alt:""},
on:{click:e.closeDialog}}),
o("div",
{staticClass:"wechatpay-content"},
[o("h3",
[e._v("请使用微信扫码支付")]),
e.wechatPayImg?o("img",
{attrs:{src:e.wechatPayImg,
alt:"集智学园"}}):o("span",
{staticClass:"icon iconfont icon-jiazai rotateInfinit",
staticStyle:{display:"inline-block",
"font-size":"26px"}})])]):e._e(),
e.showAlipayDialog?o("div",
{staticClass:"wrapper login animated fadeIn"},
[o("img",
{staticClass:"close-btn",
attrs:{src:n("1be4"),
alt:""},
on:{click:e.closeDialog}}),
o("div",
{staticClass:"alipay-content"},
[o("h3",
[e._v("请前往支付宝收银台进行操作...")]),
o("button",
{on:{click:e.closeDialog}},
[e._v("支付遇到问题")]),
o("button",
{staticClass:"success",
on:{click:e.paySuccess}},
[e._v("支付成功")])])]):e._e()])},
D=[],
k=(n("efce"),
n("ed8b"),
n("4634"),
n("e4e2")),
P=n("cabd"),
S=n("c24f"),
T=(n("1376"),
n("08c1"));function I(e,
t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);t&&(o=o.filter((function(t){return Object.getOwnPropertyDescriptor(e,
t).enumerable}))),
n.push.apply(n,
o)}return n}function L(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?I(n,
!0).forEach((function(t){Object(k["a"])(e,
t,
n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,
Object.getOwnPropertyDescriptors(n)):I(n).forEach((function(t){Object.defineProperty(e,
t,
Object.getOwnPropertyDescriptor(n,
t))}))}return e}var O={data:function(){return{showTips:!1,
loginType:"wechat",
showRegister:!1,
login:{},
register:{},
resetPassword:{},
wechatLoginInterval:null,
wechatPayImg:"",
courseInfo:{},
wechatPayTime:null,
courseDetailstatus:!1,
wxloginstate:""}},
mounted:function(){var e=this;if(this.showWechatpayDialog)this.wechatPay(this.courseDetail.cid);else if(this.showAlipayDialog);else{var t=this.getCookie(),
n=parseInt((new Date).getTime()/2592e5);this.login={username:t[" user"]||t["user"],
password:t["pas_wnnns_".concat(n)]||t[" pas_wnnns_".concat(n)]},
this.openLoginDialog(!0),
this.$nextTick((function(){e.setIntervalWechatLogin()}))}},
computed:Object(T["c"])(["showLoginDialog",
"showWechatpayDialog",
"showAlipayDialog",
"courseDetail"]),
methods:L({},
Object(T["b"])(["openLoginDialog",
"openAliPayDialog",
"openWechatPayDialog",
"setLoading"]),
{getCookie:function(){var e=document.cookie.split(";"),
t={};return e.forEach((function(e){t[e.split("=")[0]]=e.split("=")[1]})),
t},
refreshLoginState:function(){this.wxloginstate=MD5((new Date).getTime().toString()+parseInt(100*Math.random()).toString())},
setIntervalWechatLogin:function(){var e=this;this.wechatLoginInterval=setInterval((function(){var t=window.location.href,
n=t.split("code="),
o=n[n.length-1];o&&S["a"].isLogin().then((function(t){"1"===t.code&&t.data&&(clearInterval(e.wechatLoginInterval),
e.loginSuccess())}))}),
1e3)},
changeLoginType:function(e){if(this.loginType=e,
"wechat"===e)this.setIntervalWechatLogin();else{clearInterval(this.wechatLoginInterval),
this.wechatLoginInterval=null,
this.resetPassword={},
this.register={};var t=this.getCookie();this.resetPassword.remobile=t[" user"]||t["user"]}},
loginkeyDown:function(e){13===e.keyCode&&this.loginBtn()},
loginBtn:function(){var e=this,
t=this.login;t.username?t.password?(this.setLoading(!0),
S["a"].login(t).then((function(n){e.setLoading(!1),
"1"===n.code?(document.cookie="user=".concat(t.username),
document.cookie="pas_wnnns_".concat(parseInt((new Date).getTime()/2592e5),
"=").concat(t.password),
e.loginSuccess()):e.$message.error(n.data)}))):this.$message.error("请输入密码"):this.$message.error("请输入用户名")},
loginSuccess:function(){this.$message.success("登录成功"),
this.closeDialog(),
this.$store.dispatch("User/setUserinfo"),
this.$store.dispatch("setCourseDetail",
this.courseInfo.cid||this.$store.state.courseDetail.cid),
this.$emit("loginSuccess")},
closeDialog:function(){clearInterval(this.wechatLoginInterval),
clearInterval(this.wechatPayTime),
this.openLoginDialog(!1),
this.openAliPayDialog(!1),
this.openWechatPayDialog(!1)},
registerKeyDown:function(e){13===e.keyCode&&this.registerBtn()},
registerBtn:function(){var e=this,
t=this.register;t.username?t.mobile?t.code?t.pwd?t.repwd?t.repwd===t.pwd?S["a"].register(t).then((function(t){"1"===t.code?(e.$message.success("注册成功，将自动登录.."),
e.login={username:e.register.username,
password:e.register.repwd},
setTimeout((function(){e.loginBtn()}),
1e3)):e.$message.info(t.data)})).catch((function(t){e.$message.error(t)})):this.$message.error("两次密码不一致"):this.$message.error("请重复密码"):this.$message.error("请输入密码"):this.$message.error("请输入验证码"):this.$message.error("请输入手机号"):this.$message.error("请输入用户名")},
forgetPasswordKeyDown:function(e){13===e.keyCode&&this.forgetPassword()},
forgetPassword:function(){var e=this,
t=this.resetPassword;t.remobile?t.recode?t.newpwd?t.repwd?t.repwd===t.newpwd?S["a"].getbackPsw(t).then((function(t){"1"===t.code?(e.$message.success("修改密码成功,
 即将自动登录.."),
e.login={username:e.resetPassword.remobile,
password:e.resetPassword.repwd},
setTimeout((function(){e.loginBtn()}),
1e3)):e.$message.error(t.data)})).catch((function(t){e.$message.error("修改失败！")})):this.$message.error("两次密码不一致"):this.$message.error("请重复密码"):this.$message.error("请输入新密码"):this.$message.error("请输入验证码"):this.$message.error("请输入手机号")},
codeBtn:function(e){var t=this,
n={type:"forget"===this.loginType?1:0,
mobile:e};n.mobile?S["a"].getCode(n).then((function(e){if("1"===e.code){t.$message.success(e.data),
t.codeText="60s";var n=60,
o=setInterval((function(){n--,
t.codeText=n+"s",
0===n&&(clearInterval(o),
t.codeText="获取验证码")}),
1e3)}else t.$message.error(e.data)})).catch((function(e){t.$message.error(e)})):this.$message.error("请输入手机号")},
toRouter:function(e){this.closeDialog(),
this.$router.push({name:e})},
wechatPay:function(e){var t=this;P["a"].wechatPay(e).then((function(e){"1"===e.code?(t.wechatPayImg=e.data.url,
t.setIntervalwechatPay()):(t.payCodeImg="",
t.$message.error(e.info))}))},
setIntervalwechatPay:function(){var e=this;this.wechatPayTime=setInterval((function(){e.courseDetailstatus||(e.courseDetailstatus=!0,
P["a"].courseDetail(e.courseDetail.cid).then((function(t){"1"===t.code&&(e.courseDetailstatus=!1,
e.$store.commit("setCourseDetail",
t.data),
1===t.data.access&&(clearInterval(e.wechatPayTime),
e.paySuccess()))})))}),
1e3)},
paySuccess:function(){var e=this;this.$store.dispatch("User/setUserinfo"),
this.$store.dispatch("setCourseDetail",
this.courseDetail.cid).then((function(t){if(1===t.access){var n={url:"paysuccess",
log_type:1,
session_id:sessionStorage.getItem("session_id")};e.$store.dispatch("setPvuv",
n);var o=e.courseDetail.award_score?parseInt(e.courseDetail.award_score)+parseInt(e.courseDetail.price):e.courseDetail.price;e.$message.success("支付成功~恭喜您获得".concat(o,
"积分")),
e.$router.push({name:"play",
query:{id:t.cid}})}else e.$message.info("抱歉，您未完成支付哦")})),
this.closeDialog()}})},
$=O,
x=(n("cc83"),
Object(b["a"])($,
C,
D,
!1,
null,
"3af1ae7e",
null)),
A=x.exports,
j=n("019a"),
B=n.n(j),
U={components:{Loading:_,
LoginDialog:A,
noticeBar:function(){return n.e("chunk-ae0974fa").then(n.bind(null,
"2512"))},
command:function(){return n.e("chunk-35e8c89d").then(n.bind(null,
"6b6f"))}},
data:function(){return{traceData:{}}},
computed:Object(T["c"])(["showLoginDialog",
"showAlipayDialog",
"showWechatpayDialog"]),
watch:{$route:function(e,
t){this.traceData.url=window.location.href,
this.trace()}},
mounted:function(){var e=this,
t=B()((new Date).getTime().toString()+parseInt(100*Math.random()).toString());sessionStorage.getItem("session_id")||sessionStorage.setItem("session_id",
t),
this.traceData={url:window.location.href,
log_type:1,
session_id:sessionStorage.getItem("session_id")},
window.onbeforeunload=function(){e.traceData.url="",
e.trace()},
this.$store.dispatch("User/setUserinfo"),
this.$store.dispatch("setCatalog")},
methods:{trace:function(){this.$store.dispatch("setPvuv",
this.traceData)}}},
V=U,
E=(n("7c55"),
Object(b["a"])(V,
g,
p,
!1,
null,
null,
null)),
R=E.exports,
N=n("c478"),
K=function(){var e=this,
t=e.$createElement,
n=e._self._c||t;return n("div",
{staticClass:"home"},
[n("Nav")],
1)},
J=[],
q=n("3d01"),
W={name:"home",
components:{Nav:q["default"]}},
G=W,
M=Object(b["a"])(G,
K,
J,
!1,
null,
null,
null),
z=M.exports;f["default"].use(N["a"]);var Y=new N["a"]({base:"/play",
mode:"history",
routes:[{path:"/video",
name:"video",
component:function(){return n.e("chunk-69861bb0").then(n.bind(null,
"298a"))}},
{path:"/",
name:"home",
component:z},
{path:"/about",
name:"about",
component:function(){return n.e("about").then(n.bind(null,
"f820"))}},
{path:"/play",
name:"play",
component:function(){return n.e("chunk-91abb970").then(n.bind(null,
"6390"))}},
{path:"/coursedetail",
name:"coursedetail",
component:function(){return n.e("chunk-538e9ed4").then(n.bind(null,
"b6c1"))}},
{path:"/search",
name:"search",
component:function(){return n.e("chunk-2c815b76").then(n.bind(null,
"1ef7"))}},
{path:"/user",
component:function(){return n.e("chunk-61383428").then(n.bind(null,
"e72b"))},
children:[{name:"record",
path:"record",
component:function(){return n.e("chunk-6122a942").then(n.bind(null,
"2b1f"))}},
{name:"info",
path:"info",
component:function(){return n.e("chunk-56967e76").then(n.bind(null,
"7ca0"))}},
{name:"score",
path:"score",
component:function(){return n.e("chunk-86a93e48").then(n.bind(null,
"7348"))}}]}]}),
F={videoInfo:{},
showPlay:!1,
player:null,
searchContent:{data:[]},
searchValue:"",
showRecomandCourse:!1},
Q={setShowRecomandCourse:function(e,
t){e.showRecomandCourse=t},
setVideoInfo:function(e,
t){e.videoInfo=t},
setShowPlay:function(e,
t){e.showPlay=t}},
Z={},
H={namespaced:!0,
state:F,
mutations:Q,
actions:Z},
X=n("f62d"),
ee={score:0,
userInfo:{},
recordList:[],
loginState:!1,
learnTotal:0},
te={setLearnTotal:function(e,
t){e.learnTotal=t},
setUserinfo:function(e,
t){e.userInfo=t||{}},
setScore:function(e,
t){e.score=t||0},
isLogin:function(e,
t){e.loginState=t},
setRecordList:function(e,
t){e.recordList=t||[]}},
ne={recordListPoint:function(e,
t,
n,
o){return e.recordList.map((function(e){return o.singlecourseMap.get(e.cid)||{}}))}},
oe={setUserinfo:function(e){var t=e.commit,
n=e.dispatch;return new Promise((function(e,
o){S["a"].isLogin().then((function(o){n("setCourseDetail",
null,
{root:!0}),
"1"===o.code&&(e(),
o.data?(t("setUserinfo",
o.data),
t("isLogin",
!0),
n("setUserScore")):(t("setScore",
0),
t("isLogin",
!1)))})).catch((function(e){}))}))},
setUserScore:function(e){var t=e.commit;S["a"].getScore().then((function(e){"1"===e.code&&t("setScore",
e.data)}))},
getStudyRecord:function(e){var t=e.commit;return new Promise((function(e,
n){S["a"].getCourse(2).then((function(o){"1"===o.code?(t("setRecordList",
o.data),
e()):n(o.info)})).catch((function(e){n(e)}))}))}},
ae={namespaced:!0,
state:ee,
getters:ne,
actions:oe,
mutations:te},
ie=(n("db3e"),
{searchContent:{data:[]},
total:0,
currentPage:1,
searchValue:""}),
se={setPage:function(e,
t){e.currentPage=t},
setTotal:function(e,
t){e.total=t},
setSearchContent:function(e,
t){e.searchContent=t},
setSearchValue:function(e,
t){e.searchValue=t}},
re={setSearchList:function(e,
t){var n=e.commit,
o=t.value,
a=t.page,
i=void 0===a?1:a;if(n("setSearchValue",
o),
n("setSearchContent",
{data:[]}),
o)return new Promise((function(e,
t){P["a"].search(o,
i).then((function(o){if("1"===o.code){var a=o;a.data=a.data?a.data:[],
n("setSearchContent",
a),
n("setTotal",
o.total||0),
e(o)}else t(o.data)})).catch((function(e){t(e)}))}))}},
ce={namespaced:!0,
state:ie,
mutations:se,
actions:re};f["default"].use(T["a"]);var ue=new T["a"].Store({state:{isShowCommand:!1,
catalogList:[],
loading:!1,
showLoginDialog:!1,
showAlipayDialog:!1,
showWechatpayDialog:!1,
courseDetailState:!1,
courselink:{},
courseVideo:[],
courseDetail:{}},
mutations:{setshowCommand:function(e,
t){e.isShowCommand=t},
setcourseDetailState:function(e,
t){e.courseDetailState=t},
setCourseDetail:function(e,
t){e.courseDetail=t},
setCourseVideo:function(e,
t){e.courseVideo=t},
getCatalog:function(e,
t){e.catalogList=t},
setLoading:function(e,
t){e.loading=t},
openLoginDialog:function(e,
t){e.User.loginState&&t||(e.showLoginDialog=t)},
openWechatPayDialog:function(e,
t){e.showWechatpayDialog=t},
openAliPayDialog:function(e,
t){e.showAlipayDialog=t}},
actions:{setCourseDetail:function(e,
t){var n=e.commit,
o=e.state;return!t||o.courseDetailState?o.courseDetail:(n("setLoading",
!0),
n("setcourseDetailState",
!0),
new Promise((function(e,
o){P["a"].courseDetail(t).then((function(t){n("setLoading",
!1),
"1"===t.code?(t.data.courseList,
n("setCourseDetail",
t.data),
n("setcourseDetailState",
!1),
e(t.data)):o(t.info)})).catch((function(e){o(e),
n("setLoading",
!1)}))})))},
setCourseVideo:function(e,
t){var n=e.commit,
o=e.state;if(t&&!o.courseDetailState)return n("setLoading",
!0),
n("setcourseDetailState",
!0),
new Promise((function(e,
o){P["a"].getVideo(t).then((function(t){n("setLoading",
!1),
"1"===t.code?(n("setCourseVideo",
t.data),
n("setcourseDetailState",
!1),
e(t)):o(t.info)})).catch((function(e){o(e),
n("setLoading",
!1)}))}))},
setCatalog:function(e){var t=e.commit;return new Promise((function(e,
n){P["a"].getCatalog().then((function(o){"1"===o.code?(o.data.push({title:"知识星空",
id:0}),
t("getCatalog",
o.data),
e()):n(o.info)})).catch((function(e){n(e)}))}))},
setPvuv:function(e,
t){e.commit;return t.time=parseInt((new Date).getTime()/1e3),
new Promise((function(){X["a"].trace(t)}))}},
modules:{User:ae,
Search:ce,
Course:H}});function le(){return de.apply(this,
arguments)}function de(){return de=Object(o["a"])(regeneratorRuntime.mark((function e(){var t;return regeneratorRuntime.wrap((function(e){while(1)switch(e.prev=e.next){case 0:return t=document.createElement("div"),
e.abrupt("return",
t);case 2:case"end":return e.stop()}}),
e)}))),
de.apply(this,
arguments)}function fe(){var e=window.navigator.userAgent.toLowerCase();return"micromessenger"===e.match(/MicroMessenger/i)}f["default"].use(d.a),
f["default"].use(u.a),
f["default"].prototype.$message=r.a,
f["default"].prototype.$confirm=i.a.confirm,
le().then((function(e){document.body.appendChild(e)})),
f["default"].prototype.$isWeiXin=fe(),
new f["default"]({router:Y,
store:ue,
render:function(e){return e(R)}}).$mount("#app");var ge=window.location.href;if(window.innerWidth<=765)if(ge.indexOf("coursedetail")>=0){var pe=ge.split("coursedetail?id=")[1]||10531;window.location.href="/mobile/courseDetail?id=".concat(pe)}else if(ge.indexOf("play/play")>=0){var he=ge.split("play?id=")[1]||10531;window.location.href="/mobile/courseDetail?id=".concat(he)}else window.location.href="/mobile/"},
"7c55":function(e,
t,
n){"use strict";var o=n("d670"),
a=n.n(o);a.a},
"7f7f":function(e,
t,
n){},
bf39:function(e,
t,
n){"use strict";var o=n("7f7f"),
a=n.n(o);a.a},
c24f:function(e,
t,
n){"use strict";var o=n("1e04"),
a={isLogin:function(){return o["a"].get("/mobileinterface/dologin")},
login:function(e){return o["a"].post("/mobileinterface/login?username",
e)},
setCode:function(e){return o["a"].get("/mobileinterface/pagetoken?code=".concat(e))},
loginOut:function(){return o["a"].get("/mobileinterface/logout")},
register:function(e){return o["a"].post("/mobileinterface/register",
e)},
getbackPsw:function(e){return o["a"].post("/mobileinterface/getbackpwd",
e)},
getCode:function(e){return o["a"].get("/sendsms/send?mobile=".concat(e.mobile,
"&type=").concat(e.type))},
userDetail:function(){return o["a"].get("/mobileinterface/userdetail")},
editUserInfo:function(e){return o["a"].post("/mobileinterface/moddetail",
e)},
editPsw:function(e){return o["a"].post("/mobileinterface/changpwd",
e)},
getScore:function(){return o["a"].get("/mobileinterface/howmuch")},
doBind:function(e){return o["a"].get("/mobileinterface/dobind?type=".concat(e))},
binding:function(e){return o["a"].post("/mobileinterface/binding",
e)},
getCourse:function(e){var t=arguments.length>1&&void 0!==arguments[1]?arguments[1]:1;return 2===parseInt(e)?o["a"].get("/mobileinterface/learnhistory?page=".concat(t)):3===parseInt(e)?o["a"].get("/mobileinterface/purchasehistory?page=".concat(t)):o["a"].get("/mobileinterface/mywant?page=".concat(t))}};t["a"]=a},
cabd:function(e,
t,
n){"use strict";var o=n("1e04"),
a={courseDetail:function(e){return o["a"].get("/mobileinterface/coursedetail?cid=".concat(e,
"&&origin=1"))},
getVideo:function(e){return o["a"].get("/newmobileinterface/getvideo?cid=".concat(e))},
getUrl:function(e){var t=arguments.length>1&&void 0!==arguments[1]?arguments[1]:"";return o["a"].get("/newmobileinterface/geturl?cid=".concat(e,
"&&pid=").concat(t,
"&&origin=1"))},
getKeyValues:function(e){return o["a"].get("/mobileinterface/tagwithword?cid=".concat(e))},
getCatalog:function(){return o["a"].get("/mobileinterface/cataloglist")},
wechatPay:function(e){return o["a"].get("/ordercenter/weixinapi?cid=".concat(e,
"&&origin=1"))},
alipay:function(e){return o["a"].get("/alipay/pcstar?cid=".concat(e,
"&&origin=1"))},
scorePay:function(e){return o["a"].get("/mobileinterface/scorepurchase?cid=".concat(e,
"&&origin=1"))},
traceVideo:function(e){return o["a"].post("/interface/trackofvideo",
e)},
search:function(e){var t=arguments.length>1&&void 0!==arguments[1]?arguments[1]:0,
n=arguments.length>2&&void 0!==arguments[2]?arguments[2]:10;return o["a"].get("/mobileinterface/searchnew?search=".concat(e,
"&&page=").concat(t,
"&&perpage=").concat(n))},
getNotice:function(){return o["a"].get("/announce/announceit")},
wantcourse:function(e,
t){return o["a"].get("/mobileinterface/wantcourse?cid=".concat(e,
"&&status=").concat(t?1:0,
"&&origin=1"))},
setLearntime:function(e,
t,
n){return o["a"].get("/mobileinterface/setlearntime?cid=".concat(e,
"&&pcid=").concat(t,
"&&time=").concat(n))},
courseRate:function(e,
t,
n){return o["a"].get("/mobileinterface/courserate?cid=".concat(e,
"&&pcid=").concat(t,
"&&rate=").concat(n))},
getratecurrent:function(e,
t){return o["a"].get("/mobileinterface/courseratecurrent?cid=".concat(e,
"&&pcid=").concat(t))}};t["a"]=a},
cc83:function(e,
t,
n){"use strict";var o=n("4c22"),
a=n.n(o);a.a},
cf05:function(e,
t,
n){e.exports=n.p+"statics/img/logo.9e6a1e58.png"},
d670:function(e,
t,
n){},
f62d:function(e,
t,
n){"use strict";var o=n("1e04"),
a={submitCommond:function(e){return o["a"].post("/interface/sendfeedback",
e)},
trace:function(e){return o["a"].post("/interface/track",
e)}};t["a"]=a}});
//# sourceMappingURL=app.4927590f.js.map